# Cloudflare Wrangler Configuration File
# Used for local development and wrangler deployments

name = "mcqsolve"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "mcqsolve-dbs"
database_id = "7814d969-73fe-41f6-ae33-bfb3c026ce22"
